// Types for Bio
export const GET_BIO = 'GET_BIO';
export const UPDATE_BIO = 'UPDATE_BIO';

// Types for Gallery
export const GET_GALLERY = 'GET_GALLERY';
export const ADD_GALLERYITEM = 'ADD_GALLERYITEM';
export const UPDATE_GALLERYITEM = 'UPDATE_GALLERYITEM';
export const DELETE_GALLERYITEM = 'DELETE_GALLERYITEM';

// Types for TattooGallery
export const GET_TATTOOGALLERY = 'GET_TATTOOGALLERY';
export const ADD_TATTOOGALLERYITEM = 'ADD_TATTOOGALLERYITEM';
export const UPDATE_TATTOOGALLERYITEM = 'UPDATE_TATTOOGALLERYITEM';
export const DELETE_TATTOOGALLERYITEM = 'DELETE_TATTOOGALLERYITEM';
